spring:
  application:
    name: training
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/training}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:R4xeNO6r1jq05OaFX3ax17b6pEmunt2MnMogRaUj94s=}
  expiration-ms: 86400000

jaas:
  app-id: ${JAAS_APP_ID:your-app-id}
  kid: ${JAAS_KID:your-key-id}
  private-key-path: ${JAAS_PRIVATE_KEY_PATH:classpath:jaas.pk}
  ttl-minutes: ${JAAS_TTL_MINUTES:60}

